# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BzActiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('used_time', models.DateTimeField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_active_code',
            },
        ),
        migrations.CreateModel(
            name='BzArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=256)),
                ('summary', models.CharField(default='', max_length=512)),
                ('contents', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_articles',
            },
        ),
        migrations.CreateModel(
            name='BzLikeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('operate', models.SmallIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_like_log',
            },
        ),
        migrations.CreateModel(
            name='BzSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=256)),
                ('source_type', models.SmallIntegerField(default=1)),
                ('spider_id', models.IntegerField(default=0)),
                ('refresh_freq', models.IntegerField(default=30)),
                ('last_refresh_time', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=64, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_source',
            },
        ),
        migrations.CreateModel(
            name='BzSpiders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(db_index=True, max_length=64)),
                ('spider_filename', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_spiders',
            },
        ),
        migrations.CreateModel(
            name='BzUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('status', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('role', models.PositiveSmallIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_user',
            },
        ),
        migrations.CreateModel(
            name='BzUserLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='0.0.0.0', max_length=16)),
                ('login_time', models.DateTimeField(blank=True, default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.BzUser')),
            ],
            options={
                'db_table': 'bz_user_login_log',
            },
        ),
        migrations.AddField(
            model_name='bzarticles',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.BzSource'),
        ),
    ]
