# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzsource',
            name='proxy',
            field=models.IntegerField(default=0),
        ),
    ]
