# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_bzsource_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzarticles',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
