# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_bzarticles_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bzarticles',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
