# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_bzarticles_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BzSourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, default='', max_length=64)),
                ('group_desc', models.CharField(default='', max_length=256)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bz_source_group',
            },
        ),
        migrations.AddField(
            model_name='bzsource',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
