# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20170305_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bzsource',
            name='author',
            field=models.CharField(default='', max_length=64),
        ),
    ]
